### ISSUE TITLE
KeeWeb requires HTTPS

### ISSUE THREAD

**Issue by hovertac2** [SvenC56/docker-keeweb#1]
This runs over port 80, and thus you get the error on loading:

Your browser doesn't support some important features we're using.

KdbxError: Error NotImplemented: AES-CBC not implemented

Any way to run this in HTTPS?

**Comment by SvenC56** [comment]
Hi @hovertac2,

I would suggest to run  KeeWeb behind a reverse proxy like NGINX or Traefik and handle HTTPS with them.

**Comment by hovertac2** [comment]
That worked!

For those who find this via google:

I used a self signed cert to test (https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-apache-in-ubuntu-16-04), but you can use LetsEncrypt so you don't have to deal with SSL warnings.

```
a2enmod proxy

a2enmod proxy_http

a2enmod proxy_ajp

a2enmod rewrite

a2enmod deflate

a2enmod headers

a2enmod proxy_balancer

a2enmod proxy_connect

a2enmod proxy_html
```

And here's `/etc/apache2/sites-available/keeweb-proxy.conf`:


Note: I'm running the docker on port 81, so the startup command is: `docker run -d -p 81:80 svenc56/keeweb`

```
<VirtualHost *:443>

    SSLEngine On

    # Set the path to SSL certificate
    # Usage: SSLCertificateFile /path/to/cert.pem
    #SSLCertificateFile /etc/apache2/ssl/file.pem
    SSLCertificateFile      /etc/ssl/certs/apache-selfsigned.crt
    SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key

    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example:
    ProxyPass / http://localhost:81/
    ProxyPassReverse / http://localhost:81/

    # Or, balance the load:
    # ProxyPass / balancer://balancer_cluster_name

</VirtualHost>
```
Finally:

```bash
a2ensite keeweb-proxy

systemctl reload apache2
```
